import ExperienceCard from "@/components/ExperienceCard";
import SkillsCards from "@/components/SkillsCards";
import { ExperienceData } from "@/components/data/experience";
import dynamic from "next/dynamic";

const ExpHero = dynamic(() => import("@/components/Heros/ExpHero"), {
  loading: () => (
    <p className="h-[900px] justify-center items-center flex">Loading...</p>
  ),
});
export const metadata = {
  keywords: [
    "Digital Experience",
    "IT Innovator",
    "Technology Evolution",
    "Angular Framework",
    "Angular 14",
    "PayCard WebUI",
    "PayBoon Application",
    "Delivery Management Quality Improvement",
    "Angular Projects",
    "Project Efficiency",
    "High-Quality Solutions",
    "German Car Company",
    "3D Virtual World",
    "React",
    "Babylon",
    "Microservices",
    "Virtual Career Fair",
    "Interactive eBrochure",
    "WebAR",
    "Digital Twins",
    "Blockchain ETH NFTs",
    "E-Wallet Integration",
    "WebAR",
    "AR Apps",
    "Gamified Experiences",
    "Aircraft Flow 360",
    "AWS Amplify",
    "Real-Time Visibility",
    "Latency in Flights",
    "Advanced Marketing eXperiment Platform",
    "Seamless Self-Service Platform",
    "Ant-Design",
    "Staff Roster Scheduling",
    "React",
    "Redux",
    "Ant Design",
    "Babel",
    "Express",
    "Senior Engineer",
    "Legacy Projects",
    "Front-End Technologies",
    "Angular",
    "React",
    "C#",
    "ASP.Net Core",
    "SQL Server",
    "Active Directory Authentication",
    "Web APIs",
    "Backend Operations",
    "ASP.Net Web API",
    "Entity Framework",
    "Razor Pages",
    "Bootstrap",
    "Insurance Client",
    "Legacy Modules",
    "Senior Software Engineer",
    ".Net",
    "WPF",
    "WCF",
    "Performance Optimization",
    "KWMS Customizations",
    "Legacy Application",
    "Technical Improvement",
    "Team Efficiency",
    "IoT Middleware",
    "Microsoft .Net",
    "C#",
    "Angular",
    "Smart-Object Connectors",
    "Real-Time Execution",
    "Monitoring",
    "IoT Conference",
    "Customized GUI",
    "Xamarin",
    "Effort Estimates",
    "Implementation",
    "Development",
    "SEO",
    "Positive Coding Skills",
    "Software Engineer",
    "Gis Based Software",
    "Land Records Department",
    "Kiosk for Karnataka Land Records",
    "Lead/Mentor",
    "Knowledge Sharing",
    "Web Developer",
    "Enterprise System",
    "Payment Gateways APIs",
    "PHP",
    "SalesForce Integration",
    "Wireframes",
    "Mockups",
    "IoT",
    "GeoMapTech",
    "Gwalior",
    "India",
    "Communication",
    "Stakeholder Management",
    "Architecture",
    "XAML UI Components",
    "SQL Tables",
    "Architectural Reorganization",
    "Optimization",
    "Application Performance",
    "Hands-On Support",
    "Continuous Growth",
    "Knowledge Sharing Environment",
    "System Technologist",
    "Self-Learning",
    "Continuous Improvement",
    "Business Value",
    "System Interfaces",
    "Smart-Object Connectors",
    "Efficiency",
    "Scalability",
    "Stability",
    "Agile Methodologies",
    "Angular Frontend",
    ".Net Web APIs Backend",
    "Debugging",
    "Optimization Skills",
    "VNS Pvt. Ltd.",
    "Web Developer",
    "New Delhi",
    "India",
    "Enterprise System",
    "Payment Gateways APIs",
    "PHP",
    "SalesForce Integration",
    "Wireframes",
    "Mockups",
    "SEO",
    "Coding Skills",
    "Positive Professional Approach",
    "Software Engineer",
    "Gis Based Software",
    "Land Records Department",
    "Kiosk for Karnataka Land Records",
    "Reverse-Engineered Legacy Modules",
    "Effective Components Interoperability",
    "Code Maintainability",
    "Software for News Channel",
    "Remote Program Scheduling",
    "Channel Logos",
    "System Technologist",
    "Self-Learning",
    "Continuous Improvement",
    "Business Value",
    "System Interfaces",
    "Smart-Object Connectors",
    "Efficiency",
    "Scalability",
    "Stability",
    "IoT Middleware",
    "Microsoft .Net",
    "C#",
    "Angular",
    "Real-Time Execution",
    "Monitoring",
    "IoT Conference",
    "Customized GUI",
    "Xamarin",
    "Effort Estimates",
    "Implementation",
    "Software Engineer",
    "RTO Automation System",
    "Visual Basic",
    "Edify Software",
    "School Software",
    "Coding Skills",
    "Top Management",
    "Teachers",
    "Parents/Guardians",
    "SMS Facility",
    "News Channel Software",
    "Fully Functional News Channel",
    "Versatile Skillset Showcase",
    "Web 3.0",
    "Solidity",
    "Web3.js",
    "Hardhat",
    "Ethers.js",
    "Metamask",
    "OpenZeppelin",
    "Three.js",
    "Languages",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "C# / C-Sharp",
    "ASP.Net",
    "DotNet Core",
    "PHP",
    "WPF / XAML",
    "Visual Basic 6.0",
    "Databases",
    "MySQL",
    "MS Access",
    "SQL Server",
    "Oracle",
    "MongoDB",
    "PostgreSQL",
    "DynamoDB",
    "Firebase",
    "XML",
    "JSON",
    "Backend",
    "NodeJS",
    "ExpressJS",
    "GraphQL",
    "NestJS",
    "AppSync",
    "Entity Framework",
    "ASP.Net Web API",
    "SOAP API",
    "AD Auth",
    "Nebular Auth",
    "WCF",
    "Frontend",
    "Bootstrap",
    "Ant Design",
    "Tailwind CSS",
    "NextJS",
    "React",
    "Angular",
    "AWS-Amplify",
    "Gatsby",
    "React Redux",
    "Redux Reducer",
    "Redux Saga",
    "Babel",
    "Craco",
    "Webpack",
    "Material UI",
    "ASP Razor Pages",
    "Nebular Theme",
    "jQuery",
    "DevOps & Tools",
    "Confluence",
    "Docker",
    "Kubernetes",
    "Salesforce",
    "AJAX",
    "MapObjects",
    "AWS",
    "GCP",
    "Jenkins",
    "Git",
    "GitLab",
    "Bitbucket",
    "JIRA",
    "Trello",
    "SonarQube",
    "Figma",
    "ArcGIS",
    "Microservices"
  ],
  title: "Extensive Experience | Digital Journey Of An IT Innovator With Depth",
  description: "Driving Technological Progress For Nearly Two Decades With A Crafting Excellence Of Tech Evolution"
};

const Experience = () => {
  return (
    <section>
      <ExpHero />
      {ExperienceData.sort((a,b)=>new Date(b.startDate)- new Date(a.startDate)).map((exp, index) => (
        <ExperienceCard
          key={index}
          ExpData={...exp}
        />
      ))}
      <SkillsCards show="all" />
    </section>
  );
};

export default Experience;
