import ProjectCards from "@/components/ProjectCards";
import dynamic from "next/dynamic";

const ProjectHero = dynamic(() => import("@/components/Heros/ProjectHero"), {
  loading: () => (
    <p className="h-[900px] justify-center items-center flex">Loading...</p>
  ),
});
export const metadata = {
  keywords: [
    "Frontend",
    "Bootstrap",
    "Ant Design",
    "Tailwind CSS",
    "NextJS",
    "React",
    "Angular",
    "AWS-Amplify",
    "Gatsby",
    "React Redux",
    "Redux Reducer",
    "Redux Saga",
    "Babel",
    "Craco",
    "Webpack",
    "Material UI",
    "ASP Razor Pages",
    "Nebular Theme",
    "jQuery",
    "Backend",
    "NodeJS",
    "ExpressJS",
    "GraphQL",
    "NestJS",
    "AppSync",
    "Entity Framework",
    "ASP.Net Web API",
    "SOAP API",
    "AD Auth",
    "Nebular Auth",
    "WCF",
    "Web 3.0",
    "Solidity",
    "Web3.js",
    "Hardhat",
    "Ethers.js",
    "Metamask",
    "OpenZeppelin",
    "DevOps & Tools",
    "Confluence",
    "Docker",
    "Kubernetes",
    "Salesforce",
    "AJAX",
    "MapObjects",
    "AWS",
    "Jenkins",
    "Git",
    "GitLab",
    "Bitbucket",
    "JIRA",
    "Trello",
    "SonarQube",
    "Figma",
    "ArcGIS",
    "Microservices",
    "Languages",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "C# / C-Sharp",
    "ASP.Net",
    "DotNet Core",
    "PHP",
    "WPF / XAML",
    "Visual Basic 6.0",
    "Databases",
    "MySQL",
    "MS Access",
    "SQL Server",
    "MongoDB",
    "DynamoDB",
    "XML",
    "JSON",
    "Aircraft 360°",
    "Marketing eXperiment Platform 2.0",
    "RTO Automation System",
    "Edify School Software",
    "Kerla Land Records GIS",
    "Help PC Online",
    "IoT Middleware platform",
    "Kerry Warehouse Management System",
    "AIA Biometric Web Application",
    "geoTIME: Workforce Management",
    "URL Shortner",
    "Order Management",
    "iAMohit: Mohit's Portfolio",
    "Birth ’n’ Death Automation System",
    "Arm License Automation System",
    "Tandem (HeroHonda Workshop Management)",
    "DinBhar News Automation",
    "SADA (Special Area Development Authority)",
    "Petronas Fire Alarm",
    "Smart Training : train the trainers",
    "Live Pricing Stocks Trading",
    "Mastroify: An Astrology App",
    "Insurance Frontend",
    "Cloud Digitize",
    "Averis Dashboard",
    "Movie Cinema Films",
    "Vehicle Parking System",
    "Virtualify Softwares & Consultancy",
    "Nakshatra Speaks : Astrology",
    "Tanjong Golden Village - TGV Cinemas",
    "Softec (Smart Conference)",
    "California University of Business and Technology",
    "SportsToto: Sports Betting",
    "Benz Minting NFTs",
  ],
  title:
    "Innovative Projects | Crafting Future Through Digital Innovations And Tech Evolution",
  description:
    "Unveiling A Gallery Of Cutting-Edge Endeavors That Define Tomorrow's Possibilities.",
};

const Projects = () => {
  return (
    <section>
      <ProjectHero />
      <h3 className="text-4xl lg:text-3xl xl:text-4xl text-center capitalize text-[#f5f543] py-8 font-semibold">
        Projects Showcase
      </h3>
      <ProjectCards />
    </section>
  );
};

export default Projects;
